### ISSUE TITLE
bug: "(0, d.createOpenAI) is not a function" when creating a new LLM connection (v3.225.4)

### ISSUE THREAD

**Issue by thorion21** [langfuse/langfuse#16549]
### Describe the bug

Creating a new LLM connection in Project Settings → LLM Connections fails with the error (0 , d.createOpenAI) is not a function. The connection is never saved, so the Playground cannot be used.

The error appears immediately after clicking "Create connection". It occurred on our previous version and persists after upgrading to 3.225.4. Clearing browser cache and testing in an incognito window did not help.

createOpenAI appears to be the factory from @ai-sdk/openai, so this looks like a module resolution / bundling issue rather than a configuration problem. Since the error does not mention the provider, API key, or base URL, it does not seem to be a connectivity or credentials issue.

### Steps to reproduce

1. Go to Project Settings → LLM Connections
2. Click "Add LLM Connection"
3. Select adapter: OpenAI
4. Provide name and token
5. Click "Create connection"
-> Error (0 , d.createOpenAI) is not a function is shown; no connection is created

### Langfuse Cloud or self-hosted?

Self-hosted

### If self-hosted, what version are you running?

v3.225.4 OSS

### SDK and integration versions

<img width="1496" height="703" alt="Image" src="https://github.com/user-attachments/assets/dba39e66-07ed-4c7e-b934-3705d8c424dc" />

### Additional information

This happens even if I toggle the "Use Responses API" option.

UPDATE:
This happens only on hardened images. We've used the following ones from DockerHub:
[Langfuse 3.x](https://hub.docker.com/hardened-images/catalog/dhi/langfuse/images/langfuse%2Fdebian-13%2F3/sha256-e6f1b5485a80382f24366e8367231b1ebda57b18c764c9b42582e42215a545e0)
[Langfuse Worker 3.x](https://hub.docker.com/hardened-images/catalog/dhi/langfuse-worker/images/langfuse-worker%2Fdebian-13%2F3/sha256-875de7e1eca2044b8be75d650639a6b182af931cb141f0582c7ee168449d2675)

Downgrading to v3.225.0 and using an image that is not hardened fixed this issue.

### Are you interested in contributing a fix for this bug?

No

**Comment by hassiebp** [comment]
Thanks for raising this - could you please check whether this persists for you on Langfuse v4?

**Comment by thorion21** [comment]
Update from the ops team:

This happens only on hardened images. We've used the following ones from DockerHub:
[Langfuse 3.x](https://hub.docker.com/hardened-images/catalog/dhi/langfuse/images/langfuse%2Fdebian-13%2F3/sha256-e6f1b5485a80382f24366e8367231b1ebda57b18c764c9b42582e42215a545e0)
[Langfuse Worker 3.x](https://hub.docker.com/hardened-images/catalog/dhi/langfuse-worker/images/langfuse-worker%2Fdebian-13%2F3/sha256-875de7e1eca2044b8be75d650639a6b182af931cb141f0582c7ee168449d2675)

Downgrading to v3.225.0 and using an image that is not hardened fixed this issue.
Unfortunately, I'm not able to test with v4.

**Comment by nimarb** [comment]
hi @thorion21 , thank you for the report.
The DHI images are not provided by us and therefore we don't support those. Can you try running our images: https://hub.docker.com/r/langfuse/langfuse/tags
those should be free of any reported vulnerabilities which are applicable.

thank you!
